### ISSUE TITLE
Module build failed: Error: Debug Failure. False expression

### ISSUE THREAD

**Issue by zeshanvirk** [ngx-translate/core#1181]
Getting the module build failed error in Agnular  "@angular/cli": "^6.1.0",

Running the build in prod mode with aot enabled. 

The complete error is 

ERROR in ./node_modules/@ngx-translate/core/fesm5/ngx-translate-core.js
Module build failed: Error: Debug Failure. False expression.
    at Object.assertDefined (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:4507:13)
    at getJSDocHost (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:10547:25)     
    at getHostSignatureFromJSDoc (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:10533:46)
    at Object.getParameterSymbolFromJSDoc (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:10524:20)
    at checkJSDocParameterTag (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:47154:21)
    at checkSourceElement (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:49806:28)
    at Object.forEach (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1792:30)    
    at checkSourceElement (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:49738:24)
    at Object.forEach (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1792:30)    
    at checkBlock (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:47525:20)       
    at checkSourceElement (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:49831:28)
    at checkIfStatement (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:47912:13) 
    at checkSourceElement (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:49837:28)
    at Object.forEach (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1792:30)    
    at checkSourceFileWorker (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:50023:20)
    at checkSourceFile (D:\jonasdocumentclient\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:49991:13)  
 @ ./src/app/core/login/login.component.ngfactory.js 17:0-42 46:183-202
 @ ./src/app/app.component.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by gsouzavd** [comment]
I got it working after replacing the latest @ngx-translate/core with a older version @ngx-translate/core@9.1.1 .

**Comment by mahiaayush** [comment]
Hey @gsouzavd , could you please explain me that how to do it.

**Comment by gsouzavd** [comment]
@mahiaayush, use the command "npm install {{module}}@{{version}}"
It should be something like:
npm install @ngx-translate/core@9.1.1

**Comment by yudiz-aman** [comment]
Hey, @mahiaayush I have used below versions for the translation It's working fine.

**"@ngx-translate/core": "^11.0.1",
"@ngx-translate/http-loader": "^4.0.0"**

Change version of these plugins and run **npm i** command then it will work fine for you.

**Comment by mhatrebhushan** [comment]
ERROR in ./node_modules/ng-apexcharts/fesm5/ng-apexcharts.js any solution for this for prod time error
