### ISSUE TITLE
I was getting "Error: No provider for t" during AoT compilation and found out that was happening because I had

### ISSUE THREAD

**Issue by Mimisss** [ngx-translate/core#1366]
I was getting "Error: No provider for t" during AoT compilation and found out that was happening because I had
```
constructor(
   translate: TranslateService
  ) {
```
in my component, but in the same time pipes were working. I replaced direct injection of `TranslateService` with
```
constructor(
    protected injector: Injector
  ) {
```
and 
```
ngOnInit() {
    this.injector.get(TranslateService).get(...
```
in ngOnInit. Now it's working. I hope that will help to somebody. Still not sure why AoT build not working properly when you injecting directly, I think related to when `TranslateService` created/provided.

_Originally posted by @bobrosoft in https://github.com/ngx-translate/core/issues/209#issuecomment-325331085_

I face the following situation:

In an angular 6.1.0 application, in a *library*, there is a *shared* module whose job is to make translations available to the whole application:

```
import { Injector, NgModule } from "@angular/core";
import { TranslateService } from '@ngx-translate/core';
import { MY_LOCALES } from './i18n/index';
@NgModule({
})

export class SharedModule {
    constructor(private _translateService: TranslateService) {
        this.ngOnInit().catch(err => {
            console.log('An error occurred while loading shared module');
            console.error(err);
        });
    }  

    static forRoot() {
        return {
            ngModule: SharedModule
        };
    }

    async ngOnInit() {
        Object.keys(MY_LOCALES).forEach(lang => {
            if (MY_LOCALES.hasOwnProperty(lang)) {
            this._translateService.setTranslation(lang, MY_LOCALES[lang], true);
            }
        });
    }
}
```

The above shared module is eagerly loaded in the app module:

```
@NgModule({
    imports: [
        BrowserModule,
        HttpClientModule,
        TranslateModule.forRoot(),
        SharedModule.forRoot(),
        ),
    ],
    bootstrap: [AppComponent],
})
export class AppModule {
}
```

The above works on development machine "A" and on the production server *BUT* does not work on any other development machines where the code is copied over from machine "A". Building is successful but the following error shows up in the browser's console:

```
Error: StaticInjectorError(AppModule)[SharedModule -> TranslateService]: 
  StaticInjectorError(Platform: core)[SharedModule -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (vendor.js:106544:19)
    at resolveToken (vendor.js:106782:24)
    at tryResolveToken (vendor.js:106726:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (vendor.js:106623:20)
    at resolveToken (vendor.js:106782:24)
    at tryResolveToken (vendor.js:106726:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (vendor.js:106623:20)
    at resolveNgModuleDep (vendor.js:113851:29)
    at _createClass (vendor.js:113896:29)
    at _createProviderInstance (vendor.js:113868:26)
```

The above error is fixed by what @bobrosoft proposed above. God knows why. On top of that, once the application runs with the fix, it always runs even if the code is reverted back to before the fix. This is random code with random behavior which is what I see more often than not in Angular.

**Comment by aki-ks** [comment]
Try importing `TranslateModule.forChild()` in your `SharedModule`

```typescript
@NgModule({
  imports: [
    TranslateModule.forChild(),
  ]
})
export class SharedModule {
    constructor(private _translateService: TranslateService) {
      ...
    }
}
```
