### ISSUE TITLE
Karma Jasmine Error: DI Error NoProviderError.ZoneAwareError (webpack:///~/zone.js/dist/zone.js:811:0 <- src/polyfills.ts:1971:33)

### ISSUE THREAD

**Issue by kamok** [ngx-translate/core#478]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I'm currently using Ionic 2. I was able to get a custom translation loader which I will later replace with calls to a service. However, when I'm trying to inject `ng2-translate` into my test suite, I'm having a cryptic stack trace that I can't decipher.

Allow me to describe how I set up `ng2-translate`.
I have a `components.module`, as configured like the Clicker Starter App [here](https://github.com/lathonez/clicker/tree/master/src). That get's exported onto the man `app.module`. In the `components.module`, I have this inside the import array:

```
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    })

// You apparently need to do this for Ionic 2. https://github.com/ngx-translate/core#aot
export function createTranslateLoader(http: Http): TranslationLoaderService {
  return new TranslationLoaderService(http);
}
```

My TranslationLoaderService looks like this. Very basic. :
```
export class TranslationLoaderService implements TranslateLoader {

  constructor(private http: Http) {
  }
  getTranslation(lang: string): Observable<any> {
    if (lang === 'en') {
      return Observable.of({
        HELLO: 'Hi there'
      });
    }else {
      return Observable.of({
        HELLO: 'Hola'
      });
    }
  }
}
```
The component works, it languages can be changed and params are passed in no problem.

Now, when try to run my init test, I get the "Missing pipe 'translate' " error. Which is a good indication that I have yet to inject the TranslateService. No problem:
```
public static configureIonicTestingModule(components: Array<any>): typeof TestBed {
    return TestBed.configureTestingModule({
      declarations: [
        ...components
      ],
      providers: [
        App, Form, Keyboard, DomController, MenuController, NavController,
        {provide: Platform, useClass: PlatformMock},
        {provide: Config, useClass: ConfigMock},
        TranslateService
      ],
      imports: [
        FormsModule,
        IonicModule,
        ReactiveFormsModule,
        **TranslateModule.forRoot({
          provide: TranslateLoader,
          useFactory: (createTranslateLoader),
          deps: [Http]
        })**
      ]
    });
  }
```
But this is where I'm stuck. Here's the stack trace:
```
Error: DI Error
	    at NoProviderError.ZoneAwareError (webpack:///~/zone.js/dist/zone.js:811:0 <- src/polyfills.ts:1971:33)
	    at NoProviderError.BaseError [as constructor] (webpack:///~/@angular/core/src/facade/errors.js:26:0 <- src/test.ts:10281:16)
	    at NoProviderError.AbstractProviderError [as constructor] (webpack:///~/@angular/core/src/di/reflective_errors.js:53:0 <- src/test.ts:71079:16)
	    at new NoProviderError (webpack:///~/@angular/core/src/di/reflective_errors.js:102:0 <- src/test.ts:71128:16)
	    at ReflectiveInjector_._throwOrNull (webpack:///~/@angular/core/src/di/reflective_injector.js:994:0 <- src/test.ts:121545:19)
	    at ReflectiveInjector_._getByKeyDefault (webpack:///~/@angular/core/src/di/reflective_injector.js:1031:0 <- src/test.ts:121582:25)
	    at ReflectiveInjector_._getByKey (webpack:///~/@angular/core/src/di/reflective_injector.js:981:0 <- src/test.ts:121532:25)
	    at ReflectiveInjector_.get (webpack:///~/@angular/core/src/di/reflective_injector.js:743:0 <- src/test.ts:121294:21)
	    at TestBed.get (webpack:///~/@angular/core/bundles/core-testing.umd.js:818:0 <- src/test.ts:60999:67)
	    at CompiledTemplate.proxyViewClass.AppView.injectorGet (webpack:///~/@angular/core/src/linker/view.js:152:0 <- src/test.ts:122303:45)
	    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (webpack:///~/@angular/core/src/linker/view.js:580:0 <- src/test.ts:122731:49)
	    at CompiledTemplate.proxyViewClass.View_HomeView_Host0.createInternal (/DynamicTestModule/HomeView/host.ngfactory.js:15:113)
	    at CompiledTemplate.proxyViewClass.AppView.createHostView (webpack:///~/@angular/core/src/linker/view.js:108:0 <- src/test.ts:122259:21)
	    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (webpack:///~/@angular/core/src/linker/view.js:564:0 <- src/test.ts:122715:52)
	    at ComponentFactory.create (webpack:///~/@angular/core/src/linker/component_factory.js:226:0 <- src/test.ts:50447:25

Error: Uncaught (in promise): Error: DI Error
	    at resolvePromise (webpack:///~/zone.js/dist/zone.js:501:0 <- src/polyfills.ts:1661:31) [ProxyZone]
	    at resolvePromise (webpack:///~/zone.js/dist/zone.js:486:0 <- src/polyfills.ts:1646:17) [ProxyZone]
	    at webpack:///~/zone.js/dist/zone.js:535:0 <- src/polyfills.ts:1695:17 [ProxyZone]
	    at ProxyZoneSpec.onInvokeTask (webpack:///~/zone.js/dist/proxy.js:103:0 <- src/test.ts:136266:39) [ProxyZone]
	    at ZoneDelegate.741.ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:274:0 <- src/polyfills.ts:1434:40) [ProxyZone]
	    at Zone.741.Zone.runTask (webpack:///~/zone.js/dist/zone.js:151:0 <- src/polyfills.ts:1311:47) [<root> => ProxyZone]
	    at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:433:0 <- src/polyfills.ts:1593:35) [<root>]
```
**Please tell us about your environment:**

* **ngx-translate version:** x.x.x
`"ng2-translate": "^5.0.0"`
 
* **Browser:** 
Chrome

**Comment by lathonez** [comment]
@kamok 

Not sure exactly what the issue is, at some point recently we've lost what provider we're missing in these errors.

For what it's worth, the following is a working `test.ts` for ngTranslate on an Ionic app. I do remember it being fiddly to get right.

```javascript
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import './polyfills.ts';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/async-test';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/fake-async-test';

import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { getTestBed, TestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';
import { App, Config, Form, IonicModule, Keyboard, DomController, GestureController, MenuController, NavController, NavParams, Platform } from 'ionic-angular';
import { ConfigMock, NavMock, NavParamMock, PlatformMock } from './mocks';
import { TranslateModule} from 'ng2-translate/ng2-translate';
import { AuthHttpService } from './pages/services/auth-http.services';
import { AuthService } from './pages/services/auth.service';
import { ApiEndpointService } from './pages/services/api-endpoint.service';
import { CategoryService } from './pages/services/category.service';
import { ItemService } from './pages/services/item.service';
import { MenuService } from './pages/services/menu.service';
import { RestaurantService } from './pages/services/restaurant.service';
import { LanguageService } from './pages/services/language.service';
import { MenuServiceMock } from './pages/services/menu.mock';
import { LanguageServiceMock } from './pages/services/language.mock';
import { OrderService } from './pages/services/order.service';

// import { BaseRequestOptions, ConnectionBackend, Http, Response, ResponseOptions } from '@angular/http';
// import { MockBackend } from '@angular/http/testing';


// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare var __karma__: any;
declare var require: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function (): void {
  // noop
};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
);
// Then we find all the tests.
const context: any = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
// Finally, start Karma to run the tests.
__karma__.start();

export class TestUtils {

  public static beforeEachCompiler(components: Array<any>): Promise<{fixture: any, instance: any}> {
    return TestUtils.configureIonicTestingModule(components)
      .compileComponents().then(() => {
        let fixture: any = TestBed.createComponent(components[0]);
        return {
          fixture: fixture,
          instance: fixture.debugElement.componentInstance,
        };
      });
  }

  public static configureIonicTestingModule(components: Array<any>): typeof TestBed { //TODO somewhere i have to add the code of services mock backend stuff
    return TestBed.configureTestingModule({
      declarations: [
        ...components,
      ],
      providers: [
        App, Form, Keyboard, DomController, GestureController, MenuController,
        {provide: Platform, useClass: PlatformMock},
        {provide: Config, useClass: ConfigMock},
        {provide: NavController, useClass: NavMock},
        {provide: NavParams, useClass: NavParamMock},
        {provide: MenuService, useClass: MenuServiceMock},
        {provide: LanguageService, useClass: LanguageServiceMock},
        AuthService, ApiEndpointService, AuthHttpService,
        CategoryService, ItemService, RestaurantService, OrderService
      ],
      imports: [
        TranslateModule.forRoot(),
        FormsModule,
        IonicModule,
        ReactiveFormsModule,
      ],
    });
  }

  // http://stackoverflow.com/questions/2705583/how-to-simulate-a-click-with-javascript
  public static eventFire(el: any, etype: string): void {
    if (el.fireEvent) {
      el.fireEvent('on' + etype);
    } else {
      let evObj: any = document.createEvent('Events');
      evObj.initEvent(etype, true, false);
      el.dispatchEvent(evObj);
    }
  }
}
```

Instead of doing your `createTranslateLoader`, I proxied the translations through `karma.conf.js`:

```javascript
    proxies: {
      '/i18n': '/base/src/assets/languages',
    }
```

However, I think the way you have done it looks more correct.

Hope this helps.

**Comment by kamok** [comment]
@lathonez Thanks, will test later. The way you're doing it is still static loading a `.json` file. I'm building a custom translation loader which does not use any static assets, so using a proxy wouldn't work. It will work for someone using a StaticLoader. 

BTW, I started migrating to the new ionic-test-example as per your deprecation. I hope it's at least as good as yours =). Hope you'll still be active around these waters.

**Comment by lathonez** [comment]
> I'm building a custom translation loader which does not use any static assets, so using a proxy wouldn't work.

My misunderstanding - sorry. You are probably safe to ignore the above then as it seems likely it wont work for you.
