### ISSUE TITLE
facing issue while running ./node_modules/.bin/ng-xi18n 

### ISSUE THREAD

**Issue by balr404** [ngx-translate/core#483]
When i am running  ./node_modules/.bin/ng-xi18n , 
I am getting the below error 

Error encountered resolving symbol values statically. Expression form not supported (position 18:4 in the original .ts file), resolving symbol AppModule in 
/testapplcation/node_modules/@angular/cli/blueprints/ng/files/__path__/app/app.module.ts

  at positionalError (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25935:39)
    at simplifyInContext (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25772:31)
    at StaticReflector.simplify (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25786:17)
    at StaticReflector.annotations (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25282:64)
    at NgModuleResolver.resolve (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:17762:86)
    at CompileMetadataResolver.getNgModuleMetadata (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:18263:64)
    at addNgModule (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25044:62)
    at /testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25055:18
    at Array.forEach (native)
    at _createNgModules (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25054:30)
Extraction failed
balaji:ngui-frontend balaji$ ./node_modules/.bin/ng-xi18n
Error: Error encountered resolving symbol values statically. Expression form not supported (position 18:4 in the original .ts file), resolving symbol AppModule in /testapplcation/node_modules/@angular/cli/blueprints/ng/files/__path__/app/app.module.ts
    at positionalError (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25935:39)
    at simplifyInContext (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25772:31)
    at StaticReflector.simplify (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25786:17)
    at StaticReflector.annotations (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25282:64)
    at NgModuleResolver.resolve (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:17762:86)
    at CompileMetadataResolver.getNgModuleMetadata (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:18263:64)
    at addNgModule (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25044:62)
    at /testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25055:18
    at Array.forEach (native)
    at _createNgModules (/testapplcation/node_modules/@angular/compiler/bundles/compiler.umd.js:25054:30)
Extraction failed

Can someone guide me to reslove this issue

**Comment by bedag-moo** [comment]
ng-xi18n is developed by the angular team, and has nothing to with ngx-translate ...

**Comment by SamVerschueren** [comment]
Like @bedag-moo said, it has nothing to do with this library so open an issue in the Angular repository instead.

**Comment by glebmachine** [comment]
Can't found your issue there, could you share link please?
I've got exact the same error

**Comment by SamVerschueren** [comment]
I don't think @balr404 already created one. So go ahead and do it yourself :).
