### ISSUE TITLE
Transpiler missing when using AoT

### ISSUE THREAD

**Issue by DevJaBo** [ngx-translate/core#541]
**I'm submitting a ...**  
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I'm using ngx-translate with SystemJS without transpiler. All works fine. Now I'm using AoT. Compiling the App works fine, but when the App starts I get this error:

```
Error loading http://localhost:26454/traceur
Unable to load transpiler to transpile http://localhost:26454/node_modules/@ngx-translate/core/index.js
Error loading http://localhost:26454/node_modules/@ngx-translate/core/index.js as "@ngx-translate/core/index" from http://localhost:26454/app/aot/app/modules/app/app.module.ngfactory.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) XHR error (404 Not Found) 
```
**What is the expected behavior?**
Due to the fact that it works with no AoT + no Transpiler it should work with AoT + no transpiler too.

**Please tell us about your environment:**

* **Angular version:** 4.0.0
* **ngx-translate version:** 6.0.1
* **ngx-translate/http-loader version:** 0.0.3
* **SystemJS:** 0.19.39
 
* **Browser:** [Chrome 58.0.3029.110 | IE 11.296.15063.0 ]

**Comment by ocombe** [comment]
If you're using systemjs, you should load `@ngx-translate/core/bundles/core.umd.js` instead of index if you don't want a transpiler.

**Comment by DevJaBo** [comment]
Hi Oliver. Thanks for the answer. Yes, i'm using SystemJS. Ok, in the first case i was loading ngx-transplate as a package:
```
//Part of old system.config.js
packages: {
          [...]
            '@ngx-translate/core': { main: '/bundles/core.umd.js', defaultExtension: 'js' },
            '@ngx-translate/http-loader': { main: '/bundles/http-loader.umd.js', defaultExtension: 'js' }
        }
```
No i'm just mapping it like in your demo-plkr but without transpiler/typescriptOptions.
Heres my system.config.js:

```
//Current system.config.js
(function (global) {
    System.config({
        //transpiler: 'typescript',
        //typescriptOptions: {
        //    emitDecoratorMetadata: true
        //},
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'app',
            '@ngx-translate/core': 'npm:@ngx-translate/core/bundles/core.umd.js',
            '@ngx-translate/http-loader': 'npm:@ngx-translate/http-loader/bundles/http-loader.umd.js',

            // angular bundles
            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/router/upgrade': 'npm:@angular/router/bundles/router-upgrade.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
            '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'systemjs-angular-loader.js'
                    }
                }
            },
            rxjs: {
                defaultExtension: 'js'
            }
       }
    });
})(this);
```  
In JiT-Mode the app is loaded without error. In AoT-Mode there is no transpile error any more. But now i'm getting the following error (i think that's why i was loading ngx as a package before):
```
Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:26454/node_modules/@ngx-translate/core/bundles/core.umd.js/src/translate.parser
	Error: XHR error (404 Not Found) loading http://localhost:26454/node_modules/@ngx-translate/core/bundles/core.umd.js/src/translate.parser
	   at wrapFn (http://localhost:26454/node_modules/zone.js/dist/zone.js:1199:17) [<root>]
	   at Zone.prototype.runTask (http://localhost:26454/node_modules/zone.js/dist/zone.js:165:21) [<root> => <root>]
	   at invoke (http://localhost:26454/node_modules/zone.js/dist/zone.js:460:21) [<root>]
	Error loading http://localhost:26454/node_modules/@ngx-translate/core/bundles/core.umd.js/src/translate.parser as "@ngx-translate/core/src/translate.parser" from http://localhost:26454/app/aot/app/modules/app/app.module.ngfactory.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:26454/node_modules/@ngx-translate/core/bundles/core.umd.js/src/translate
```

**Comment by CodeAndWeb** [comment]
I am closing this issue for now...
Please submit a new issue if the problem still persists.
