### ISSUE TITLE
ng2 translate does not work with webpack

### ISSUE THREAD

**Issue by Shifs** [ngx-translate/core#608]
For reducing the start time of the application, I have configured webpack in my application . But after that ng2 translate is not working and I am getting the error 
ERROR Error: Uncaught (in promise): Response with status: 200  for URL: null

 "ng2-translate": "^5.0.0",

**Comment by Shifs** [comment]
I have updated ng2 translate and now using ng-x- translate but still getting the same issue

**Comment by Shifs** [comment]
The error is 
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'get' of undefined
JS: TypeError: Cannot read property 'get' of undefined
JS:     at TranslateHttpLoader.module.exports.TranslateHttpLoader.getTranslation (file:///data/data/org.nativescript.sai/files/app/bundle.js:48300:25)
JS:     at TranslateService.module.exports.TranslateService.getTranslation (file:///data/data/org.nativescript.sai/files/app/bundle.js:305:55)
JS:     at TranslateService.module.exports.TranslateService.retrieveTranslations (file:///data/data/org.nativescript.sai/files/app/bundle.js:292:87)
JS:     at TranslateService.module.exports.TranslateService.use (file:///data/data/org.nativescript.sai/files/app/bundle.js:266:28)
JS:     at new LoginComponent (file:///data/data/org.nativescript.sai/files/app/bundle.js:14038:24)
JS:     at createClass (file:///data/data/org.nativescript.sai/files/app/vendor.js:11328:26)
JS:     at createDirectiveInstance (file:///data/data/org.nativescript.sai/files/app/vendor.js:11152:37)
JS:     at createViewNodes (file:///data/data/org.nativescript.sai/files/app/vendor.js:12501:49)
JS:     at createRootView (file:///data/data/org.nativescript.sai/files/app/vendor.js:12406:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.sai/files/app/vendor.js:13537:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.sai/files/app/vendor.js:12998:12)
JS:     at ComponentFactory_.module.exports.ComponentFactory_.create (file:///data/data/org.nativescript.sai/files/app/vendor.js:10343:46)
JS:     at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.sai/files/app/vendor.js:3924:29)
JS:     at ViewContainerRef_.module.exports.ViewContainerRef_.createComponent (file:///data/data/org.nativescript.sai/files/app/vendor.js:10543:62)
JS:     at PageRouterOutlet.module.exports.PageRouterOutlet.activateOnGoForward (file:///data/data/org.nativescript.sai/files/app/vendor.js:30208:55)
```

**Comment by Cayan** [comment]
I had a similar issue a few hours ago, if your translation json is inside the folder app/assets/i18n
add the next line to your CopyWebpackPlugin
{ from: "assets/i18n/*.json" }

**Comment by Shifs** [comment]
@Cayan : Tried that too .. still the error is same. Can you please share your app.module.ts

**Comment by Cayan** [comment]
@Shifs the related code from app.module.ts is listed below:

...
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
...
export function createTranslateLoader(http: Http) {
    return new TranslateHttpLoader(http);
}

@NgModule({
    schemas: [NO_ERRORS_SCHEMA],
    imports: [
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: (createTranslateLoader),
                deps: [Http]
            }
        }),
...

**Comment by mozi22** [comment]
@Shifs  did you solve this issue ?
