### ISSUE TITLE
Unable to install core package

### ISSUE THREAD

**Issue by rotemx** [ngx-translate/core#679]
**I'm submitting a ...**
[X] support request

**Current behavior**
When trying to install using `npm install @ngx-translate/core --save` I get the following error: 

[> 
> [       ...........] | extract:@ngx-translate/core: verb lock using C:\Users\rotemx\AppData\Roaming\npm-cache\_locks\staging-19dfb0af
> [       ...........] | extract:@ngx-translate/core: verb lock using C:\Users\rotemx\AppData\Roaming\npm-cache\_locks\staging-19dfb0af
> [       ...........] | extract:@ngx-translate/core: verb lock using C:\Users\rotemx\AppData\Roaming\npm-cache\_locks\staging-19dfb0af
> [       ...........] | extract:@ngx-translate/core: verb lock using C:\Users\rotemx\AppData\Roaming\npm-cache\_locks\staging-19dfb0af
> [       ...........] | extract:@ngx-translate/core: verb lock using C:\Users\rotemx\AppData\Roaming\npm-cache\_locks\staging-19dfb0af
> [       ...........] | extract:@ngx-translate/core: verb lock using C:\Users\rotemx\AppData\Roaming\npm-cache\_locks\staging-19dfb0af
> [       ...........] | extract:@ngx-translate/core: verb lock using C:\Users\rotemx\AppData\Roaming\npm-cache\_locks\staging-19dfb0af
> [       ...........] | extract:@ngx-translate/core
> core: verb lock using C:\Users\myRepo\AppData\Roaming\npm-cache\_locks\staging-19dfb0afnpm WARN myRepo@0.0.1 No repository field.
> npm WARN myRepo@0.0.1 No license field.
> 
> **npm ERR! Cannot read property '0' of undefined**
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\[username]\AppData\Roaming\npm-cache\_logs\2017-09-26T12_36_46_407Z-debug.log`
> 
> 
]

* this is the log data for the error :

```
2797 verbose stack TypeError: Cannot read property '0' of undefined
2797 verbose stack     at rmStuff (C:\Program Files\nodejs\node_modules\npm\lib\unbuild.js:61:24)
2797 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
2797 verbose stack     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
2797 verbose stack     at lifecycle.then.then (C:\Program Files\nodejs\node_modules\npm\lib\install\action\unbuild.js:12:12)
2797 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
2797 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
2797 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
2797 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
2797 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
2797 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
2797 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
2797 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
2797 verbose stack     at runCallback (timers.js:781:20)
2797 verbose stack     at tryOnImmediate (timers.js:743:5)
2797 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)

```

**Expected/desired behavior**
The package installs successfully.

**Reproduction of the problem**
I'm not sure where this is reproducible.

**Please tell us about your environment:**
Win 10 - os build 14393.1715
node v8.5.0
npm 5.3.0
my repo is Angular 4.4.3 with WebPack 3.0.11

* **ngx-translate version:** 
latest

* **Angular version:** 
4.4.3
 
* **Browser:** N/A

**Edit: **
This was an issue with NPM v5.3.0 under Windows 10. 
Downgrading to NPM 5.2.0 solved the issue.

**Comment by rotemx** [comment]
This was an issue with NPM v5.3.0 under Windows 10.
Downgrading to NPM 5.2.0 solved the issue.
