### ISSUE TITLE
Unhandled Promise rejection: Object(...) is not a function Promise.then ; Value: TypeError: Object(...) is not a function in ionic3?

### ISSUE THREAD

**Issue by kapilSoni101** [ngx-translate/core#950]
## Current behavior ##
Got above error after ionic serve 

## Expected behavior ##
 After ionic serve app is open 

## Environment

<pre><code>
ngx-translate version: X.Y.Z
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
`polyfills.js:3 Unhandled Promise rejection: Object(...) is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Object(...) is not a function
    at new ApplicationRef (vendor.js:15312)
    at _createClass (vendor.js:18294)
    at _createProviderInstance (vendor.js:18256)
    at initNgModule (vendor.js:18189)
    at new NgModuleRef_ (vendor.js:18916)
    at Object.createNgModuleRef (vendor.js:18905)
    at NgModuleFactory_.create (vendor.js:21464)
    at vendor.js:15117
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:14655) TypeError: Object(...) is not a function
    at new ApplicationRef (http://localhost:8100/build/vendor.js:15312:64)
    at _createClass (http://localhost:8100/build/vendor.js:18294:20)
    at _createProviderInstance (http://localhost:8100/build/vendor.js:18256:26)
    at initNgModule (http://localhost:8100/build/vendor.js:18189:32)
    at new NgModuleRef_ (http://localhost:8100/build/vendor.js:18916:9)
    at Object.createNgModuleRef (http://localhost:8100/build/vendor.js:18905:12)
    at NgModuleFactory_.create (http://localhost:8100/build/vendor.js:21464:25)
    at http://localhost:8100/build/vendor.js:15117:43
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:14655:33)
n.onUnhandledError @ polyfills.js:3
`
Steps to reproduce:
From cmd >  npm i @ngx-translate/core@9.1.1

# Version used #

li packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : not installed

local packages:
    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:
    Node : v8.10.0
    npm  : 6.3.0 
    OS   : Linux 4.13

Environment Variables:
    ANDROID_HOME : /home/Android/Sdk/

**Comment by ACivilise** [comment]
https://github.com/ngx-translate/core/issues/824

**Comment by kapilSoni101** [comment]
#ACivilise  sir i have already installed this plugin but not working

**Comment by ACivilise** [comment]
Hi,
You need to install a compatible version with the angular version  used in your ionic project. 
You can look in your package.json file to know which version of angular used. 
![image](https://user-images.githubusercontent.com/8189250/47849306-5e9c3900-ddd1-11e8-930a-5ffde3e1c5b4.png)
Uninstall the package you installed and then specify the version to install like this : 
npm install @ngx-translate/core@**9.1.1** --save
npm install @ngx-translate/http-loader@**2.0.1** --save
Regards.

**Comment by binaryPUNCH** [comment]
Inheriting a project someone else made and I've been trying for way too long to make it build. Same issue as OP. Feel like I'm close but can't seem to solve this one. My ng version seems aligned with the appropriate ngx-translate.. So what's going on?

```
{
  "name": "Brick-IT",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "test": "karma start ./test-config/karma.conf.js",
    "test-ci": "karma start ./test-config/karma.conf.js --single-run",
    "test-coverage": "karma start ./test-config/karma.conf.js --coverage",
    "e2e": "npm run e2e-update && npm run e2e-test",
    "e2e-test": "protractor ./test-config/protractor.conf.js",
    "e2e-update": "webdriver-manager update --standalone false --gecko false"
  },
  "dependencies": {
    "@angular/animations": "^7.2.14",
    "@angular/common": "^7.2.14",
    "@angular/compiler": "^7.2.14",
    "@angular/compiler-cli": "^7.2.14",
    "@angular/core": "^7.2.14",
    "@angular/forms": "^7.2.14",
    "@angular/http": "^7.2.14",
    "@angular/platform-browser": "^7.2.14",
    "@angular/platform-browser-dynamic": "^7.2.14",
    "@ionic-native-mocks/qr-scanner": "^2.0.12",
    "@ionic-native/app-version": "^4.0.0",
    "@ionic-native/core": "^4.0.0",
    "@ionic-native/flurry-analytics": "^4.0.0",
    "@ionic-native/globalization": "^4.0.0",
    "@ionic-native/network": "^4.0.0",
    "@ionic-native/qr-scanner": "^4.0.0",
    "@ionic-native/splash-screen": "^4.0.0",
    "@ionic-native/status-bar": "^4.0.0",
    "@ionic/storage": "^2.2.0",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/router-store": "^7.4.0",
    "@ngrx/store": "^7.4.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/aws-sdk": "^2.7.0",
    "@types/graphql": "^14.0.3",
    "apollo-angular": "^1.5.0",
    "apollo-angular-link-http": "^1.6.0",
    "apollo-cache-inmemory": "^1.5.1",
    "apollo-client": "^2.5.1",
    "aws-amplify": "^1.1.26",
    "aws-appsync": "^1.7.2",
    "aws-sdk": "^2.442.0",
    "axios": "^0.18.0",
    "cordova-android": "^8.0.0",
    "cordova-ios": "^5.0.1",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-cocoapod-support": "^1.6.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-flurryanalytics": "^1.4.6",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.0.1",
    "cordova-plugin-native-keyboard": "^2.0.3",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-qrscanner": "^3.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.4.1",
    "graphql": "^14.2.1",
    "graphql-tag": "^2.8.0",
    "ionic-angular": "^3.9.5",
    "ionicons": "3.0.0",
    "localforage": "^1.7.2",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "random-name": "^0.1.2",
    "randomcolor": "^0.5.3",
    "rxjs": "^5.0.1",
    "rxjs-compat": "^6.5.1",
    "sw-toolbox": "^3.6.0",
    "symbol-observable": "^1.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "~7.3.8",
    "@angular/language-service": "^7.2.14",
    "@ionic/app-scripts": "^3.2.3",
    "@types/jasmine": "^3.3.12",
    "@types/node": "^11.13.7",
    "html-loader": "^0.5.5",
    "ionic3-mocks": "^0.11.22",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jasmine": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.0",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^3.0.0",
    "null-loader": "^1.0.0",
    "protractor": "^5.4.2",
    "ts-node": "^8.1.0",
    "tslint": "^5.16.0",
    "typescript": "^3.2.0"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-qrscanner": {},
      "cordova-plugin-native-keyboard": {
        "LICENSE": "TRIAL",
        "LIC_ANDROID": "TRIAL"
      },
      "cordova-plugin-globalization": {},
      "cordova-plugin-flurryanalytics": {},
      "cordova-plugin-app-version": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}

```

**Comment by kapilSoni101** [comment]
@binayPUNCH:- sir please  open the issue actually I don't need ng-translate in our app sir so tell me sir how to fix and please open it?
